// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qubix.Infrastructure.Persistence;

#nullable disable

namespace Qubix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724194732_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_AnswerOptions_QuestionId_Position");

                    b.ToTable("AnswerOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnswerOptions_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_AnswerOptions_Text", "char_length(btrim(\"Text\")) > 0");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AwardedPoints")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResponseTimeMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionQuestionId")
                        .HasDatabaseName("IX_AnswerSubmissions_SessionQuestionId");

                    b.HasIndex("ParticipantId", "SessionQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_AnswerSubmissions_ParticipantId_SessionQuestionId");

                    b.ToTable("AnswerSubmissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnswerSubmissions_AwardedPoints", "\"AwardedPoints\" >= 0");

                            t.HasCheckConstraint("CK_AnswerSubmissions_IncorrectHasNoPoints", "\"IsCorrect\" IS DISTINCT FROM FALSE OR \"AwardedPoints\" = 0");

                            t.HasCheckConstraint("CK_AnswerSubmissions_ResponseTimeMilliseconds", "\"ResponseTimeMilliseconds\" >= 0");

                            t.HasCheckConstraint("CK_AnswerSubmissions_UngradedHasNoPoints", "\"IsCorrect\" IS NOT NULL OR \"AwardedPoints\" = 0");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerSubmissionOption", b =>
                {
                    b.Property<Guid>("AnswerSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionAnswerOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("AnswerSubmissionId", "SessionAnswerOptionId");

                    b.HasIndex("SessionAnswerOptionId")
                        .HasDatabaseName("IX_AnswerSubmissionOptions_SessionAnswerOptionId");

                    b.ToTable("AnswerSubmissionOptions", (string)null);
                });

            modelBuilder.Entity("Qubix.Core.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuizSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("QuizSessionId", "Score")
                        .HasDatabaseName("IX_Participants_QuizSessionId_Score");

                    b.HasIndex("QuizSessionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Participants_QuizSessionId_UserId");

                    b.ToTable("Participants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Participants_DisplayName", "char_length(btrim(\"DisplayName\")) > 0");

                            t.HasCheckConstraint("CK_Participants_Score", "\"Score\" >= 0");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_Questions_QuizId_Position");

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_Content", "NULLIF(btrim(\"Text\"), '') IS NOT NULL OR NULLIF(btrim(\"ImageUrl\"), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_Questions_Points", "\"Points\" BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("CK_Questions_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_Questions_TimeLimitSeconds", "\"TimeLimitSeconds\" BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_Questions_Type", "\"Type\" IN ('SingleChoice', 'MultipleChoice')");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultQuestionTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rules")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("IX_Quizzes_OwnerId_Status");

                    b.ToTable("Quizzes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Quizzes_DefaultQuestionTimeSeconds", "\"DefaultQuestionTimeSeconds\" BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_Quizzes_Status", "\"Status\" IN ('Draft', 'Published', 'Archived')");

                            t.HasCheckConstraint("CK_Quizzes_Title", "char_length(btrim(\"Title\")) > 0");

                            t.HasCheckConstraint("CK_Quizzes_UpdatedAfterCreated", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentQuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentQuestionId");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_QuizSessions_QuizId");

                    b.HasIndex("RoomCode")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizSessions_ActiveRoomCode")
                        .HasFilter("\"Status\" IN ('Waiting', 'Running')");

                    b.HasIndex("OrganizerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_QuizSessions_OrganizerId_CreatedAtUtc");

                    b.ToTable("QuizSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuizSessions_FinishedAfterStart", "\"FinishedAtUtc\" IS NULL OR \"FinishedAtUtc\" >= \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_QuizSessions_Lifecycle", "(\"Status\" = 'Waiting' AND \"StartedAtUtc\" IS NULL AND \"FinishedAtUtc\" IS NULL) OR (\"Status\" = 'Running' AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NULL) OR (\"Status\" = 'Finished' AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_QuizSessions_RoomCode", "char_length(\"RoomCode\") = 6 AND \"RoomCode\" ~ '^[A-Z0-9]+$'");

                            t.HasCheckConstraint("CK_QuizSessions_Status", "\"Status\" IN ('Waiting', 'Running', 'Finished')");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.SessionAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceAnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SourceAnswerOptionId");

                    b.HasIndex("SessionQuestionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_SessionAnswerOptions_SessionQuestionId_Position");

                    b.HasIndex("SessionQuestionId", "SourceAnswerOptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SessionAnswerOptions_SessionQuestionId_SourceAnswerOptionId");

                    b.ToTable("SessionAnswerOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionAnswerOptions_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_SessionAnswerOptions_Text", "char_length(btrim(\"Text\")) > 0");
                        });
                });

            modelBuilder.Entity("Qubix.Core.Entities.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClosesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("OpensAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SourceQuestionId");

                    b.HasIndex("QuizSessionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_SessionQuestions_QuizSessionId_Position");

                    b.HasIndex("QuizSessionId", "SourceQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SessionQuestions_QuizSessionId_SourceQuestionId");

                    b.ToTable("SessionQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionQuestions_ClosedAfterOpen", "\"ClosedAtUtc\" IS NULL OR \"ClosedAtUtc\" >= \"OpensAtUtc\"");

                            t.HasCheckConstraint("CK_SessionQuestions_Content", "NULLIF(btrim(\"Text\"), '') IS NOT NULL OR NULLIF(btrim(\"ImageUrl\"), '') IS NOT NULL");

                            t.HasCheckConstraint("CK_SessionQuestions_DeadlineAfterOpen", "\"ClosesAtUtc\" IS NULL OR \"ClosesAtUtc\" >= \"OpensAtUtc\"");

                            t.HasCheckConstraint("CK_SessionQuestions_Lifecycle", "(\"Status\" = 'Pending' AND \"OpensAtUtc\" IS NULL AND \"ClosesAtUtc\" IS NULL AND \"ClosedAtUtc\" IS NULL) OR (\"Status\" = 'Open' AND \"OpensAtUtc\" IS NOT NULL AND \"ClosesAtUtc\" IS NOT NULL AND \"ClosedAtUtc\" IS NULL) OR (\"Status\" = 'Closed' AND \"OpensAtUtc\" IS NOT NULL AND \"ClosesAtUtc\" IS NOT NULL AND \"ClosedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SessionQuestions_Points", "\"Points\" BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("CK_SessionQuestions_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_SessionQuestions_Status", "\"Status\" IN ('Pending', 'Open', 'Closed')");

                            t.HasCheckConstraint("CK_SessionQuestions_TimeLimitSeconds", "\"TimeLimitSeconds\" BETWEEN 5 AND 300");

                            t.HasCheckConstraint("CK_SessionQuestions_Type", "\"Type\" IN ('SingleChoice', 'MultipleChoice')");
                        });
                });

            modelBuilder.Entity("Qubix.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_DisplayName", "char_length(btrim(\"DisplayName\")) > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerOption", b =>
                {
                    b.HasOne("Qubix.Core.Entities.Question", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerSubmission", b =>
                {
                    b.HasOne("Qubix.Core.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Core.Entities.SessionQuestion", null)
                        .WithMany()
                        .HasForeignKey("SessionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerSubmissionOption", b =>
                {
                    b.HasOne("Qubix.Core.Entities.AnswerSubmission", null)
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AnswerSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Core.Entities.SessionAnswerOption", null)
                        .WithMany()
                        .HasForeignKey("SessionAnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.Participant", b =>
                {
                    b.HasOne("Qubix.Core.Entities.QuizSession", null)
                        .WithMany("Participants")
                        .HasForeignKey("QuizSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.Question", b =>
                {
                    b.HasOne("Qubix.Core.Entities.Quiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.Quiz", b =>
                {
                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.QuizSession", b =>
                {
                    b.HasOne("Qubix.Core.Entities.SessionQuestion", null)
                        .WithMany()
                        .HasForeignKey("CurrentQuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Qubix.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Qubix.Core.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.SessionAnswerOption", b =>
                {
                    b.HasOne("Qubix.Core.Entities.SessionQuestion", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("SessionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Core.Entities.AnswerOption", null)
                        .WithMany()
                        .HasForeignKey("SourceAnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.SessionQuestion", b =>
                {
                    b.HasOne("Qubix.Core.Entities.QuizSession", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qubix.Core.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("SourceQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Qubix.Core.Entities.AnswerSubmission", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Qubix.Core.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("Qubix.Core.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Qubix.Core.Entities.QuizSession", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Qubix.Core.Entities.SessionQuestion", b =>
                {
                    b.Navigation("AnswerOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
